### ISSUE TITLE
Deleted data re-appearing

### ISSUE THREAD

**Issue by alex-akanthas** [influxdata/influxdb-client-js#861] opened 2023-07-24 08:01 UTC
### Specifications

* Client Version: @influxdata/influxdb-client-apis": "^1.21.0
* InfluxDB Version:  InfluxDB Cloud powered by TSM - Version 2.0.0
* Platform: InfluxDB Cloud powered by TSM - Version 2.0.0

### Code sample to reproduce problem

```javascript
await deleteAPI.postDelete({
          org,
          bucket: containerBucket,
          body: {
            start: startDateIsoStr,
            stop: stopDateIsoStr,
            predicate: '_measurement="'+id+'"',
          },
        });
```

### Expected behavior

Data is deleted forever

### Actual behavior

Data is completely deleted but then the data re-appears with certain only certain fields populated after 12 hours (overnight)

### Additional info

We’re running influxdb cloud 2.0. We have an issue where we delete timestamps for a given measurement via the node js api, I double check on the data explorer that the data is deleted. Then 12 hours later (overnight) the data re-appears with only some fields populated. I then delete the data again and it is deleted forever.

Could there be some overnight job which re-adds the data ?

The bucket settings are as follows: Retention: Forever, Schema Type: Implicit.

We've raised the issue at https://community.influxdata.com/t/deleted-data-re-appearing/30820 with no reponse.

**Comment by powersj** [comment] 2023-07-25 13:06
> the data re-appears with certain only certain fields populated after 12 hours (overnight)

This sounds like you have something importing your data ;) If the data gets deleted successfully and somehow overnight reappears I would be looking for a job, task, or importer that you previously set up that is importing data.

**Comment by alex-akanthas** [comment] 2023-07-26 07:29
@powersj Thanks for your message. Yes it would seem like that and that was my initial thought but there is nothing in our system that would be importing data at that time.

Anyway, I agree, that the influxdb-client-js is doing it's job as expected and that it must be a problem with influxdb itself or our system

**Comment by powersj** [comment] 2024-05-21 22:16
Were you able to ever figure out what the root cause was? Going to close this as I think we agreed it wasn't a library issue.

**Closed by powersj** 2024-05-21 22:16 UTC
Labels: question
