### ISSUE TITLE
Writes one data point and then fails (with AWS lambda)

### ISSUE THREAD

**Issue by ZaneL** [influxdata/influxdb-client-js#260] opened 2020-09-19 15:44 UTC
Hello,

I'm trying to use this library in an AWS lambda function but it will only write one data point and then it fails afterwards.

This describes the issue:
https://github.com/influxdata/influxdb/issues/18633

**Comment by sranka** [comment] 2020-09-19 17:27
Duplicate of #261, which was transferred herein from influxdata/influxdb#18633

**Closed by sranka** 2020-09-19 17:27 UTC
